resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: http://github.com/pivotalservices/pcf-pipelines.git
    branch: master

jobs:
  - name: pave-iaas
    plan:
    - get: pcf-pipelines
      trigger: true
  
    - task: pave
      file: pcf-pipelines/install-pcf/openstack/tasks/pave_openstack.yaml
      params:
        EXTERNAL_NETWORK: {{external_network}}
        INFRA_NETWORK: {{infra_network}}
        INFRA_SUBNET: {{infra_subnet}}
        ERT_NETWORK: {{ert_network}}
        ERT_SUBNET: {{ert_subnet}}
        SERVICES_NETWORK: {{services_network}}
        SERVICES_SUBNET: {{services_subnet}}
        SERVICESOD_NETWORK: {{servicesod_network}}
        SERVICESOD_SUBNET: {{servicesod_subnet}}
        ADMIN_ROUTER: {{admin_router}}
        BACKEND_ROUTER: {{backend_router}}
        OS_PROJECT_ID: {{os_project_id}}
        OS_REGION_NAME: {{os_region_name}}
        OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
        OS_PROJECT_NAME: {{os_project_name}}
        OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
        OS_PASSWORD: {{os_password}}
        OS_AUTH_URL: {{os_auth_url}}
        OS_USERNAME: {{os_username}}
        PRE_OS_CACERT: {{pre_os_cacert}}
        OS_INTERFACE: {{os_interface}}
