---
platform: linux

image_resource:
 type: docker-image
 source:
   repository: pivotalservices/openstack-tools

params:
  EXTERNAL_NETWORK:
  INFRA_NETWORK:
  OPS_MGR_FLV_NAME:
  OPS_MGR_IMG_NAME:
  OPS_MGR_KEY_NAME:
  OPS_MGR_SEC_GRP:
  OPS_MGR_SRV_NAME:
  OPS_MGR_SRV_NAME:
  PRE_OS_CACERT:

inputs:
- name: pcf-pipelines
- name: pivnet-opsman-product

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/boot-opsman/task.sh
