---

platform: linux

image_resource:
 type: docker-image
 source:
   repository: pivotalservices/openstack-tools

params:
  PRE_OS_CACERT:
  OPS_MGR_IMG_NAME:

inputs:
  - name: pivnet-opsman-product
  - name: pcf-pipelines

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/upload-product-and-stemcell.sh
